version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      ASS_HANDLER: $ASS_HANDLER
      BOT_TOKEN: $BOT_TOKEN
      DURATION_LIMIT: $DURATION_LIMIT
      LOGGER_ID: $LOGGER_ID
      MONGO_DB_URI: $MONGO_DB_URI
      OWNER_ID: $OWNER_ID
      PING_IMG: $PING_IMG
      START_IMG: $START_IMG
      SUPPORT_CHAT: $SUPPORT_CHAT
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL
      STRING_SESSION: $STRING_SESSION
      SUDO_USERS: $SUDO_USERS
