#!/bin/bash
### Dusky Music Bot Installer

pprint (){
	cred='\033[0;31m'
	cgreen='\033[0;32m'
	cyellow='\033[0;33m'
	cblue='\033[0;34m'
	cpurple='\033[0;35m'
	eval "export color='$cpurple'"
	[ ! -z $2 ] && eval "export color=\"\$$2\""
    printf "$color $1"
}

color_reset(){ printf '\033[0;37m';}

yesnoprompt(){
	old_stty_cfg=$(stty -g)
	stty raw -echo ; answer=$(head -c 1)
	stty $old_stty_cfg
	echo "$answer" | grep -iq "^y"
}

update() {
	pprint "\n\nUpdating package list.. "
	sudo apt update 2>&1 | grep "can be upgraded" &>/dev/null
	if [ $? -eq 0 ]; then
		pprint "UPDATE AVAILABLE" "cgreen"
		pprint "\n\nDo you want to automatically upgrade (y/n)?"
		if yesnoprompt; then
			pprint "\n\nUpgrading packages.. "
			sudo apt upgrade -y &>/dev/null &&
			pprint "DONE!\n\n" "cgreen" || (pprint "FAIL.\n\n" "cred"; exit 1)
		else
			echo
		fi
	else
		pprint "ALREADY UP TO DATE\n\n" "cgreen"
	fi
}

packages(){
	if ! command -v pip &>/dev/null; then
		pprint "Couldn't found pip, installing now.. "
		sudo apt install python3-pip -y 2>pypilog.txt 1>/dev/null &&
		pprint "SUCCESS.\n\n" "cgreen" || (pprint "FAIL.\n\n" "cred"; exit 1)
	fi

	if ! command -v ffmpeg &>/dev/null; then
		pprint "Couldn't found ffmpeg, installing now.. "
		if sudo apt install ffmpeg -y &>/dev/null;then
			pprint "SUCCESS.\n\n" "cgreen"
		else
			pprint "FAIL.\n\n" "cred"
			pprint "You need to install ffmpeg manually in order to use DuskyMusicBot, exiting..\n" "cblue"
			exit 1
		fi
	fi

	# Check ffmpeg version and warn user if necessary.
	fv=$(grep -Po 'version (3.*?) ' <<< $(ffmpeg -version)) &&
	pprint "Playing live streams not going to work since you have ffmpeg $fv, live streams are supported by version 4+.\n" "cblue"
}


node(){
	command -v npm &>/dev/null && return
	pprint "Installing Nodejs and Npm..  "
	curl -fssL https://deb.nodesource.com/setup_17.x | sudo -E bash - &>nodelog.txt &&
	sudo apt install nodejs -y &>>nodelog.txt &&
	sudo npm i -g npm &>>nodelog.txt &&
	pprint "SUCCESS!\n" "cgreen" || (pprint "FAIL.\n" "cred"; exit 1)
}


repo(){
	# Get git repo if the installer is runned standalone
	[[ ! "DuskyMusicBot" == $(basename -s .git `git config --get remote.origin.url`) ]] &&
	git clone https://github.com/DuskyMusic/DuskyMusicBot &&  cd DuskyMusicBot
}


installation(){
	pprint "\n\nUpgrading pip and installing dependency packages.. "
	pip3 install -U pip &>>pypilog.txt &&
	pip3 install -U -r requirements.txt &>>pypilog.txt &&
	pprint "DONE.\n" "cgreen" && return
	pprint "FAIL.\n" "cred"
	exit 1
}

clear
pprint "Welcome to Dusky Music Bot Setup Installer\n\n"
pprint "If you see any error during Installation Process, Please refer to these files for logs: "
pprint "\nFor node js errors , Checkout nodelog.txt"
pprint "\nFor pypi packages errors , Checkout pypilog.txt"
sleep 2
pprint "\n\nScript needs sudo privileges in order to update & install packages.\n"
sudo test

update
packages
node
repo
installation
pprint "\n\n\n\n\nDusky Music Bot Installation Completed!" "cgreen"
sleep 4
clear

pprint "\nEnter Your Values Below\n\n\n"
pprint "API ID: "; color_reset; api_id = "12363338"
pprint "\nAPI HASH: "; color_reset; api_hash = "4bd85e3e1269e3b06557ebfd67418319"
pprint "\nBOT TOKEN: "; color_reset; bot_token = "5698584696:AAHIPgUHW0YFUZILF5bkh4ncyOcEJelN4VY"
pprint "\nMONGO DB URI: "; color_reset; mongo_db = "mongodb+srv://kuttyangel:onlydusky@cluster0.nzfa4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
pprint "\nLOG GROUP ID: "; color_reset; logger = "-1001889152773"
pprint "\nPYROGRAM STRING SESSION OF ASSISTANT ACCOUNT: "; color_reset; string_session = "BQC5JVsr14pKGRTpU2GE-sqrPy1oUGv13wTXkrwSclLoTDFcl7WrKvsxQ2VXbuAFkPXmeAgI37DqPUcEjZdcScaKBhCt6gc1_wBYz1-r4C73B9sl_slvE3E-kjfNbdBM4AVwngP40xeuFBLmO3NAIgrqvpzizuEth_d993bMhNoJe0ClrWSqFsy9jKX27Z1F1INm3b5bgbMvUK7dx6Xrj4wuOfdZX8wQgLOj_GxKfR0yet-H4NYtTxdXMLbpx5GoAqtFToRNK42gYPFI5p8cxlPAgSOuHgoUJiNmTH4tLhdUnh_Thij8LWkhHnp7DCGpUgTD3f8fgqlkx6M87lniExb9AAAAAUkgyokA"
pprint "\nMUSIC BOT NAME: "; color_reset; mbt = "Kutty Angel"
pprint "\nOwner Id:"; color_reset; read ownid = "5696423555"

pprint "\n\nProcessing your vars, Wait a while!" "cgreen"

if [ -f .env ]; then
	rm .env
fi

echo """API_ID = $api_id
API_HASH = $api_hash
BOT_TOKEN = $bot_token
MONGO_DB_URI = $mongo_db
LOG_GROUP_ID = $logger
MUSIC_BOT_NAME = $mbt
STRING_SESSION = $string_session
OWNER_ID = $ownid""" > .env
clear
pprint "\n\n\nYour Vars have been saved Successfully!, Thanks for using Dusky Installer, now you can proceed by starting the bot with bash start!"
pprint "\n\n\nWant more vars?"
pprint "\nCheckout config.py and readme.md inside config folder for addtional vars. You can change all images , Thumbs, mode and everything from vars. Have a look towards them\n\n"
